services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: snack_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d snack_app_db" ]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 10s

#  snack-order-app-pedido:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: snack-order-app-pedido
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/snack_app_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres123
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: "true"
#    depends_on:
#      db:
#        condition: service_healthy

  rabbitmq:
    #    image: rabbitmq:4-management
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/


  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"
    environment:
      - TZ=America/Manaus
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - node_red_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:5050"
    depends_on:
      - db

volumes:
  postgres-data:
  node_red_data: